Repository awslabs/aws-athena-query-federation, pull requests merged in 2020-11, with the labels that each got.

#196 Adding URL Encoding to JDBC connection string passwords for issue 195
  athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/connection/GenericJdbcConnectionFactory.java
Labels: bug

#285 Integration-Test Suite
  athena-dynamodb/pom.xml
  athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DdbTableUtils.java
  athena-dynamodb/src/test/java/com/amazonaws/athena/connectors/dynamodb/DynamoDBIT.java
  athena-federation-sdk-tools/pom.xml
  athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/integration/ConnectorStack.java
  athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/integration/IntegrationTestBase.java
  athena-federation-sdk/pom.xml
  pom.xml
Labels: enhancement

#298 Integration-Test Suite docs.
  athena-federation-sdk-tools/README.md
  athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/integration/README.md
Labels: documentation, enhancement

#303 Fixes fasterxml.jackson-annotations dependency.
  athena-dynamodb/pom.xml
  athena-federation-sdk-tools/pom.xml
  athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/integration/README.md
  pom.xml
Labels: bug

#308 Adding support for '-e' flag to validator which allows the validator …
  athena-federation-sdk-tools/src/main/java/com/amazonaws/athena/connector/validation/ConnectorValidator.java
Labels: enhancement
